[features]
seeds = true
skip-lint = false

[programs.localnet]
transaction_example = "BhV84MZrRnEvtWLdWMRJGJr1GbusxfVMHAwc3pq92g4z"

[workspace]
members = [
    "./programs/transaction-example"
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://light-red-uranium.solana-mainnet.quiknode.pro/eddef9a00bf8a6ad49769b860e0c372b3b78e091/"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 5000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 