name: "Run Tests"
description: "Runs Anchor tests"
inputs:
  program:
    description: "Program to test"
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/extract-versions/
      id: versions

    - uses: ./.github/actions/setup/

    - uses: ./.github/actions/setup-solana/

    - uses: ./.github/actions/setup-anchor/
      with:
        anchor-version: ${{ env.ANCHOR_VERSION }}

    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules/
        key: node-modules-${{ runner.os }}-build-v0.1

    - name: Install Node.js dependencies
      shell: bash
      run: yarn install

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          test-ledger/
        shared-key: "anchor-test-${{ env.ANCHOR_VERSION }}-${{ env.SOLANA_VERSION }}"

    - name: Run Anchor Tests
      shell: bash
      env:
        CARGO_INCREMENTAL: 1
        CARGO_NET_RETRY: 10
        RUST_BACKTRACE: 1
      run: |
        echo "Running tests for program: ${{ inputs.program }}"
        anchor test

    - name: Check Test Results
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "Tests failed! Check the logs above for details."
        exit 1
