name: Reusable Test Program

on:
  workflow_call:
    inputs:
      program:
        description: "Program to test"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Woody4618/github-action/.github/actions/run-tests/@main
        with:
          program: ${{ github.event.inputs.program }}
