name: Reusable Test Program

on:
  workflow_call:
    inputs:
      program:
        description: "Program to test"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-tests/
        with:
          program: ${{ github.event.inputs.program }}
