name: Test Program

on:
  push:
    branches: ["*"]
    paths:
      - "programs/**"
      - "tests/**"
      - "Anchor.toml"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:
    inputs:
      program:
        description: "Program to test"
        required: true
        default: "transaction_example"

jobs:
  test:
    uses: ./.github/workflows/reusable_test.yaml
    with:
      program: ${{ github.event.inputs.program || 'transaction_example' }}
